import { NextRequest, NextResponse } from 'next/server';

/**
 * Catch-all proxy: /api/polymarket/relayer-proxy/[...path]
 *
 * Forwards all requests to https://relayer.polymarket.com so that the
 * Expo app never contacts polymarket.com domains directly (required for
 * regions where Polymarket is blocked, e.g. India).
 *
 * The mobile RelayClient is configured with this URL as its base URL.
 * All builder HMAC headers generated by the SDK are forwarded as-is.
 */

const TARGET = 'https://relayer-v2.polymarket.com';

// Max retries for upstream fetch failures
const MAX_RETRIES = 3;
// Fetch timeout in ms
const FETCH_TIMEOUT_MS = 15_000;

// Headers that must not be forwarded upstream
const HOP_BY_HOP = new Set([
    'host',
    'connection',
    'keep-alive',
    'proxy-authenticate',
    'proxy-authorization',
    'te',
    'trailers',
    'transfer-encoding',
    'upgrade',
]);

async function proxyRequest(
    request: NextRequest,
    params: Promise<{ path: string[] }>
): Promise<NextResponse> {
    const { path } = await params;
    const subPath = '/' + path.join('/');
    const search = request.nextUrl.search; // includes "?" if present
    const targetUrl = `${TARGET}${subPath}${search}`;

    // Build forwarded headers (strip hop-by-hop)
    const forwardHeaders = new Headers();
    request.headers.forEach((value, key) => {
        if (!HOP_BY_HOP.has(key.toLowerCase())) {
            forwardHeaders.set(key, value);
        }
    });
    // Ensure a User-Agent is set (some upstreams reject requests without one)
    if (!forwardHeaders.has('user-agent')) {
        forwardHeaders.set('user-agent', 'HunchApp/1.0 (relayer-proxy)');
    }

    const isBodyMethod = !['GET', 'HEAD'].includes(request.method.toUpperCase());
    const body = isBodyMethod ? await request.arrayBuffer() : undefined;

    let upstream: Response | undefined;
    let lastError: string = 'Unknown error';

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
        try {
            const controller = new AbortController();
            const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

            upstream = await fetch(targetUrl, {
                method: request.method,
                headers: forwardHeaders,
                body: body ? body : undefined,
                signal: controller.signal,
                // @ts-expect-error — duplex required for streaming body in Node 18+
                duplex: 'half',
            });

            clearTimeout(timeout);
            break; // success
        } catch (err: any) {
            lastError = err?.name === 'AbortError'
                ? `Timeout after ${FETCH_TIMEOUT_MS}ms`
                : (err?.message || 'fetch failed');
            console.error(`[relayer-proxy] Attempt ${attempt}/${MAX_RETRIES} failed:`, targetUrl, lastError);

            if (attempt < MAX_RETRIES) {
                // Exponential backoff: 500ms, 1500ms
                await new Promise(r => setTimeout(r, 500 * attempt));
            }
        }
    }

    if (!upstream) {
        return NextResponse.json(
            { error: 'Relayer proxy upstream error', detail: lastError },
            { status: 502 }
        );
    }

    const responseBody = await upstream.arrayBuffer();

    // Build response headers (strip hop-by-hop + stale encoding headers)
    // Node's fetch auto-decompresses gzip/br, so content-encoding &
    // content-length from upstream are stale — strip them.
    const STRIP_RESPONSE = new Set([...HOP_BY_HOP, 'content-encoding', 'content-length']);
    const responseHeaders = new Headers();
    upstream.headers.forEach((value, key) => {
        if (!STRIP_RESPONSE.has(key.toLowerCase())) {
            responseHeaders.set(key, value);
        }
    });

    return new NextResponse(responseBody, {
        status: upstream.status,
        headers: responseHeaders,
    });
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
    return proxyRequest(req, params);
}
export async function POST(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
    return proxyRequest(req, params);
}
export async function PUT(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
    return proxyRequest(req, params);
}
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
    return proxyRequest(req, params);
}
export async function DELETE(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
    return proxyRequest(req, params);
}
